# Generated by Django 3.2.5 on 2021-09-03 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birthday',
            field=models.DateField(null=True, verbose_name='誕生日'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='code',
            field=models.CharField(max_length=10, null=True, verbose_name='コード'),
        ),
    ]
