# Generated by Django 3.2.5 on 2021-09-04 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookdoor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcomment',
            name='spoiler',
            field=models.BooleanField(default=False, verbose_name=''),
        ),
        migrations.AddField(
            model_name='bookcomment',
            name='title',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
