# Generated by Django 3.1.13 on 2021-09-25 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookdoor', '0004_auto_20210925_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
            ],
        ),
    ]
